name = "BaseMicroFloats"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@ieee.org>"
uuid = "f73e857c-9931-4f62-811b-cdda1686d046"
version = "0.1.0"

[deps]
BaseFloats = "466cf478-de3d-41ed-aa97-fc1150812615"

[compat]
BaseFloats = "0.1 - 0.5"
Test = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
